Repository KartoffelToby/better_thermostat, pull requests merged in 2022-03, with the labels that each got.

#335 switch from None to isinstance
  custom_components/better_thermostat/controlling.py
Labels: enhancement

#334 Get the right setting entity from TVR
  custom_components/better_thermostat/helpers.py
Labels: bug, wait for feedback

#355 fix None check
  custom_components/better_thermostat/climate.py
  custom_components/better_thermostat/events/time.py
  custom_components/better_thermostat/events/trv.py
  custom_components/better_thermostat/models/utils.py
Labels: bug

#357 Rename "Void" to "None" in docstrings
  custom_components/better_thermostat/climate.py
  custom_components/better_thermostat/controlling.py
  custom_components/better_thermostat/events/temperature.py
  custom_components/better_thermostat/events/time.py
  custom_components/better_thermostat/events/trv.py
  custom_components/better_thermostat/events/window.py
  custom_components/better_thermostat/helpers.py
Labels: bug, documentation

#356 remove z2m requirements (not needed in 1.0)
  README.md
Labels: documentation, enhancement

#363 round local calibration to n.nn0 degree
  custom_components/better_thermostat/controlling.py
  custom_components/better_thermostat/models/utils.py
Labels: bug

#378 remove unnecessary local varibales
  custom_components/better_thermostat/climate.py
Labels: enhancement

#379 rewrite trigger_window_change() to be interruptable by new changes
  custom_components/better_thermostat/climate.py
  custom_components/better_thermostat/events/window.py
  custom_components/better_thermostat/helpers.py
Labels: bug, enhancement
