Repository KartoffelToby/better_thermostat, pull requests merged in 2022-01, with the labels that each got.

#159 current about info
  about.info
Labels: documentation

#156 Massivly simplify the readme and streamline for easy access
  README.md
  assets/z2m_legacy.png
  assets/z2m_legacy_global_1.png
  assets/z2m_legacy_global_2.png
Labels: documentation

#164 bump version to 1.0.0
  README.md
  custom_components/ai_thermostat/climate.py
  custom_components/ai_thermostat/manifest.json
Labels: chores

#165 Update about.info
  about.info
Labels: documentation

#167 fix typos
  README.md
  custom_components/ai_thermostat/climate.py
Labels: documentation

#168 Small clean up code formating
  README.md
  custom_components/ai_thermostat/climate.py
  custom_components/ai_thermostat/helpers.py
  custom_components/ai_thermostat/models/models.py
  custom_components/ai_thermostat/models/utils.py
Labels: enhancement

#171 remove old dampening code
  custom_components/ai_thermostat/models/utils.py
Labels: enhancement

#153 Add restore functions if HA restarts
  custom_components/ai_thermostat/climate.py
Labels: enhancement

#183 Readme.md: cleanup device support list and create a table for it
  README.md
Labels: documentation

#184 fix typo
  README.md
Labels: chores

#185 complete the rename
  README.md
  custom_components/better_thermostat/__init__.py
  custom_components/better_thermostat/climate.py
  custom_components/better_thermostat/helpers.py
  custom_components/better_thermostat/manifest.json
  custom_components/better_thermostat/models/devices/BRT_100_TRV.yaml
  custom_components/better_thermostat/models/devices/GS361A_H04.yaml
  custom_components/better_thermostat/models/devices/SEA801-Zigbee_SEA802-Zigbee.yaml
  custom_components/better_thermostat/models/devices/SPZB0001.yaml
  custom_components/better_thermostat/models/devices/TS0601_thermostat.yaml
  custom_components/better_thermostat/models/models.py
  custom_components/better_thermostat/models/utils.py
  custom_components/better_thermostat/services.yaml
Labels: bug

#204 Readme: create multiline entries in whitelabel row
  README.md
Labels: documentation

#170 add a license to make this project open-source (not only have publically available source code)
  LICENSE
Labels: chores

#212 Add nighttime check by time comparison
  custom_components/better_thermostat/climate.py
Labels: enhancement

#213 fix minor code comment typos
  custom_components/better_thermostat/climate.py
Labels: documentation, chores

#217 add docstrings
  custom_components/better_thermostat/helpers.py
  custom_components/better_thermostat/models/models.py
  custom_components/better_thermostat/models/utils.py
Labels: documentation

#218 rewrite startup recovery for missing setpoint
  custom_components/better_thermostat/climate.py
Labels: enhancement

#219 make errors on HVAC actions more verbose
  custom_components/better_thermostat/climate.py
Labels: enhancement

#220 make valve maintenance possible on the TS0601
  custom_components/better_thermostat/climate.py
Labels: bug, enhancement

#221 better log messages
  custom_components/better_thermostat/climate.py
Labels: documentation, enhancement

#222 improve temperature sensor update processing
  custom_components/better_thermostat/climate.py
Labels: bug

#233 [about.info] small rewording
  about.info
Labels: documentation, enhancement

#225 fix get_device_model
  custom_components/better_thermostat/climate.py
Labels: bug

#226 min/max temp + precision in the config file
  custom_components/better_thermostat/climate.py
  custom_components/better_thermostat/models/utils.py
Labels: enhancement

#232 [climate.py] BetterThermostat._async_trv_changed docstring rewrite
  custom_components/better_thermostat/climate.py
Labels: documentation

#227 add version file; set version to 1.0.0-dev
  custom_components/better_thermostat/climate.py
  custom_components/better_thermostat/manifest.json
Labels: enhancement

#247 Readme.md: Add links to maintainers
  README.md
Labels: documentation, enhancement

#240 New model identification and removal of z2m dependency
  custom_components/better_thermostat/climate.py
  custom_components/better_thermostat/helpers.py
  custom_components/better_thermostat/manifest.json
  custom_components/better_thermostat/models/models.py
Labels: enhancement
